# Generated by Django 5.2.7 on 2025-11-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_metadata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmetadata',
            name='file_location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
