# Generated by Django 5.2.7 on 2025-11-03 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_metadata', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
