# Generated by Django 5.2.7 on 2025-11-10 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_metadata', '0002_alter_assetmetadata_file_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmetadata',
            name='resolution',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
