# Generated by Django 5.2.7 on 2025-10-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmetadata',
            name='dimensions',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='assetmetadata',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetmetadata',
            name='file_size',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assetmetadata',
            name='file_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='assetmetadata',
            name='resolution',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
