# Generated by Django 5.2.7 on 2025-10-23 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0002_assetmetadata_dimensions_assetmetadata_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmetadata',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
