# Generated by Django 5.2.7 on 2025-10-29 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0003_assetmetadata_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetmetadata',
            old_name='asset_name',
            new_name='file_name',
        ),
        migrations.RenameField(
            model_name='assetmetadata',
            old_name='file',
            new_name='upload_file',
        ),
    ]
