# Generated by Django 5.2.7 on 2025-10-29 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0004_rename_asset_name_assetmetadata_file_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetmetadata',
            old_name='file_name',
            new_name='asset_name',
        ),
    ]
