# Generated by Django 5.2.7 on 2025-11-02 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metadata', '0005_rename_file_name_assetmetadata_asset_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetmetadata',
            old_name='upload_file',
            new_name='file',
        ),
    ]
